### ISSUE TITLE
switch to MIT license

### ISSUE THREAD

**Issue by mbutterick** [mbutterick/txexpr#14]
@AlexKnauth 
@zyrolasting 
@samth 
@LeifAndersen 

Consistent with [Racket’s overall relicensing](https://blog.racket-lang.org/2019/11/completing-racket-s-relicensing-effort.html) from LGPL to Apache+MIT, I’d like to move `txexpr` from the LGPL to MIT.

Because the MIT license is more permissive, this requires the assent of you, the esteemed contributors.

If you agree, please post a message saying so, e.g. — "I hereby relicense my contributions to `txexpr` under the MIT license."

On January 1, if you have not agreed to the relicensing, I will remove your code. Thanks.

**Comment by samth** [comment]
I hereby relicense my contributions to txexpr under the MIT license.

**Comment by zyrolasting** [comment]
I hereby relicense my contributions to txexpr under the MIT license.

**Comment by AlexKnauth** [comment]
I hereby relicense my contributions to txexpr under the MIT license.

**Comment by LeifAndersen** [comment]
Oh, I just saw this. Ya, I'm cool with re-licensing. :)

**Comment by mbutterick** [comment]
committed in 55720d8e280c3d1f10434b619258c98bc87b0050
