### ISSUE TITLE
bad error message in get-* functions

### ISSUE THREAD

**Issue by odanoburu** [mbutterick/txexpr#6]
```
> (get-tag "oi")
; car: contract violation
;   expected: pair?
;   given: "oi"
```

from my understanding, the `define+provide+safe` macro should be exporting `get-tag` with a contract that would raise an error blaming my call to `get-tag` not the hidden call to `car`. am I doing something wrong? or is this a bug in the `sugar` library? if so, the only way I know of fixing this is by using regular constructs like `define/contract`, hence the absence of an accompanying PR!

**Comment by mbutterick** [comment]
To get the contract you have to import via the `safe` submodule:

```racket
#lang racket
(require (submod txexpr safe))
(get-tag "oi")
```

Result:

```racket
get-tag: contract violation
  expected: txexpr?
  given: "oi"
  in: the 1st argument of
      (-> txexpr? txexpr-tag?)
  contract from: 
      (txexpr/txexpr/base.rkt safe)
  blaming: anonymous-module
   (assuming the contract is correct)
```

**Comment by odanoburu** [comment]
ah, that's interesting! sorry for the noise.
